### ISSUE TITLE
Upgraded anki and merge function isn't working

### ISSUE THREAD

**Issue by silentcicada1** [Arthur-Milchior/anki-merge-notes#1]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-03-25 09:16:47
Add-ons possibly involved: ⁨Merge two notes into a single note⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/silentcicada1/Library/Application Support/Anki2/addons21/1482505492/__init__.py", line 84, in <lambda>
    a.triggered.connect(lambda : onMerge(browser))
  File "/Users/silentcicada1/Library/Application Support/Anki2/addons21/1482505492/__init__.py", line 13, in onMerge
    note = mergeNids(browser.selectedNotes())
  File "/Users/silentcicada1/Library/Application Support/Anki2/addons21/1482505492/__init__.py", line 32, in mergeNids
    return mergeNotes(note1, note2)
  File "/Users/silentcicada1/Library/Application Support/Anki2/addons21/1482505492/__init__.py", line 55, in mergeNotes
    cards[card.ord] = card
IndexError: list assignment index out of range

**Comment by Arthur-Milchior** [comment]
Can you please export the two notes you're trying to merge and send them to me, so I'll try myself.
I don't really understand how it's possible.

Are they note of a cloze type ?
